### ISSUE TITLE
React on Special Keys like DEL / INSERT etc

### ISSUE THREAD

**Issue by thomasletsch** [UnicornHeartClub/react-keybind#14]
Hi,

I really like the lib :-). 
The problem I'm currently facing is how can I react on special keys like the delete / insert key?

Thanks,
Thomas

**Comment by tlackemann** [comment]
Thanks for the feedback.

You should be able to simply use `insert` or `delete`.

**Example**

```typescript
shortcut.registerShortcut(this.deleteItem, ['delete'], 'Remove Item', 'Removes an item from your checkout')
```
If the above isn't working, we'd be happy to write a test and figure out the best solution forward there.

**Comment by thomasletsch** [comment]
This works!

Thanks!
