### ISSUE TITLE
<ShortcutProvider /> should set event listeners on window, not div

### ISSUE THREAD

**Issue by Redmega** [UnicornHeartClub/react-keybind#42]
If you use a shortcut which causes the div to lose focus, the next use of that shortcut will trigger the browser shortcut instead (if using things like `ctrl+n`, `ctrl+s`, etc).

**Comment by tlackemann** [comment]
This has been implemented as of 0.5.0

Thanks @Redmega !

**Comment by midzer** [comment]
Using latest version, I still have issues:
When I `strg+n` Chrom* and Firefox open a new browser window, instead of calling my custom function.

Any1 have an idea what I'm doing wrong in my implementation? I followed the example closely.
