### ISSUE TITLE
shortcut with command works just the first time 

### ISSUE THREAD

**Issue by andrecrts** [UnicornHeartClub/react-keybind#466]
i have implemented the library and have a shorcut with these keys ['ctrl+s', 'cmd+s'] the one with control works fine but the one with command works just the first time and the second time it triggers the save dialog i have event.preventDefault in the provider as true and in the method that triggers the shortcut also. i dont know if im missing something

**Comment by tlackemann** [comment]
That should be all that's required.

I just wrote some tests to confirm the implementation. It works in testing but that's not to say there might be something not caught.

Could you provide a small sample case that we can debug? Would be happy to find a resolution with you.

Thank you for reporting.

**Comment by andrecrts** [comment]
Thanks for your help i have created a quick repo with an app to reproduce the error this is the [repo](https://github.com/andrecrts/react-keybind-test ) 
i am counting the times the keybind is pressed but the first time i press cmd + s works but the next time the save dialog prompts but if i press ctrl + s it works every time.

**Comment by tlackemann** [comment]
Thank you kindly! I'll be able to get around to testing this weekend at the soonest. Sincerely appreciate the repo, helps a lot.

**Comment by andrecrts** [comment]
hi @tlackemann  did you have time to test the repo?

**Comment by tlackemann** [comment]
@andrecrts If you upgrade to 0.9.3, the issue _should_ be fixed. I used your repo with the upgraded package and it was working for me on mac, would be interested if it solves the issue for you.

Thanks for your patience.

**Comment by andrecrts** [comment]
thank you very much it works!!

**Comment by tlackemann** [comment]
@andrecrts Excellent, thank you for reporting back :)

Closing.
