### ISSUE TITLE
allow bindings to <input> elements

### ISSUE THREAD

**Issue by paulsohn** [UnicornHeartClub/react-keybind#565]
Hello, I am writing a web-based editor and want to bind eventlisteners to every descendants, including `input` elements.
It seems that `input` element is ignored(denylisted) by default and there is no way to remove it.

The relevant lines on `src/index.tsx` are L188~190, saying:
```
const ignore = ignoreTagNames
      ? [...ignoreTagNames.map(tag => tag.toLowerCase()), ...ignoreForTagNames]
      : ignoreForTagNames
```

I suggest that L189 should be just
```
const ignore = ignoreTagNames
      ? ignoreTagNames.map(tag => tag.toLowerCase())
      : ignoreForTagNames
``` 

because concatenating is pointless when you want to override the default option.

**Comment by tlackemann** [comment]
This has been updated on the main branch and will be included in the next tagged release.

Thank you for raising.
