### ISSUE TITLE
make sequencing time(2s) adjustable

### ISSUE THREAD

**Issue by paulsohn** [UnicornHeartClub/react-keybind#566]
When registering sequence shortcuts, the maximum interval is set to 2000ms.
Maybe it would be nicer to let 2000ms adjustable by props.

(L264)
```
// we have 2s to keep sequencing keys otherwise we'll reset the previous array
this.sequenceTimer = window.setTimeout(() => {
        this.previousKeys = []
        this.sequenceTimer = undefined
      }, 2000)
```

**Comment by tlackemann** [comment]
This has been updated on the main branch and will be included in the next tagged release.

Thank you for raising.
